// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lftcimkllwotimqhsooh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmdGNpbWtsbHdvdGltcWhzb29oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3OTk0OTEsImV4cCI6MjA4ODM3NTQ5MX0.U5hpQtCX_xrL_2xyif6TDu_6gRACgx7sxAE5nS-qOB0";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
